server:
  port: 8085

spring:
  application:
    name: ai-service
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}

GEMINI_API_KEY: ${GEMINI_API_KEY:YOUR_DEFAULT_KEY_HERE}
APPLICATION_EVENT_SERVICE_URL: ${APPLICATION_EVENT_SERVICE_URL:http://event-service:8084}
