server.port=8084

spring.datasource.url=jdbc:postgresql://event-db:5432/ehub_event_db
spring.datasource.username=postgres
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

application.internal.gateway-secret=${GATEWAY_INTERNAL_SECRET}

# Enum deserialization
spring.jackson.mapper.accept-case-insensitive-enums=true

# Service Integration
application.common-service.url=http://common-services:8083/common
